// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Core.Data;

#nullable disable

namespace POS.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251004172230_AddDummyUsers")]
    partial class AddDummyUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@pos.com",
                            IsActive = true,
                            Name = "Admin User",
                            PasswordHash = "$2a$11$N7DHv5cF5mKz5JqKGZwNXeZw3JRj9zJ6V8yqK4xZ9tJ7k5C6V4uXy",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cxp.com",
                            IsActive = true,
                            Name = "CXP Admin",
                            PasswordHash = "$2a$11$N7DHv5cF5mKz5JqKGZwNXeZw3JRj9zJ6V8yqK4xZ9tJ7k5C6V4uXy",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "downtown@mithai.com",
                            IsActive = true,
                            Name = "Downtown Mithai Shop",
                            PasswordHash = "$2a$11$8Xvt90PQnNpxhOhqh8D8JeF3vZL8H7nJ5K9mL4pR6sT2uV1wX3yZ",
                            Role = "Shop"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mall@mithai.com",
                            IsActive = true,
                            Name = "Mall Mithai Shop",
                            PasswordHash = "$2a$11$8Xvt90PQnNpxhOhqh8D8JeF3vZL8H7nJ5K9mL4pR6sT2uV1wX3yZ",
                            Role = "Shop"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "suburb@mithai.com",
                            IsActive = true,
                            Name = "Suburb Mithai Shop",
                            PasswordHash = "$2a$11$8Xvt90PQnNpxhOhqh8D8JeF3vZL8H7nJ5K9mL4pR6sT2uV1wX3yZ",
                            Role = "Shop"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@example.com",
                            IsActive = true,
                            Name = "John Doe",
                            PasswordHash = "$2a$11$K5mZ7n8P9qR1sT2uV3wX4yZ5A6B7C8D9E0F1G2H3I4J5K6L7M8N",
                            Role = "User"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@example.com",
                            IsActive = true,
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$K5mZ7n8P9qR1sT2uV3wX4yZ5A6B7C8D9E0F1G2H3I4J5K6L7M8N",
                            Role = "User"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test@test.com",
                            IsActive = true,
                            Name = "Test User",
                            PasswordHash = "$2a$11$L6nA8o9Q0rS1tU2vW3xY4zA5B6C7D8E9F0G1H2I3J4K5L6M7N8O",
                            Role = "User"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "inactive@example.com",
                            IsActive = false,
                            Name = "Inactive User",
                            PasswordHash = "$2a$11$M7oB9p0R1sT2uV3wX4yZ5A6B7C8D9E0F1G2H3I4J5K6L7M8N9O",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
